# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: c

# GHC depends on GMP. You can add other dependencies here as well.
addons:
  apt:
    packages:
    - libgmp-dev

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

# This line does all of the work: installs GHC if necessary, build the library,
# executables, and test suites, and runs the test suites. --no-terminal works
# around some quirks in Travis's terminal implementation.
script:
- stack --no-terminal --install-ghc test

# Prepare the upload to S3
- mkdir -p to-travis
- cp $(stack exec which kube-cert) to-travis
- bzip2 to-travis/kube-cert

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: O7mMYhRENH/48DZ8CEGIXarr1324ZSbYFxEbKb4mXkEBdg8PkLBJQgXG/V9AwoiUxp8FOjwQ+mcd9xHLpO4wzWCs0A+PXi4geMd/PcmsfF/q1a49VzZhXNuUoxzahl3DPOU6+HVwWTQ9HkI1slg6Ry2m0nT8ok9FnNTUmi3dPu3Uniz1VGNatcO0oel7a5Q9I7b00OtyrnTJG6VARouBM/Ap7V28BOFuBz+kRS5K5S3gx9HfxRHSWwDFLYiEAOhYYpeqdQJMd/0JqrMrwPTAw+pubYmAdICSx0LnRkwV7LjPsOvYGwaNwjeZ6kPU7ZXZkFJQDpjKqS0J62Vg4i7HmXVVYLeKCCjlYM+pCT9B4JPcHajsY/hiqry3L87aOOcjRnoX0z7KkPvycFXN9f+ycljJPH3XbEOeGzh7IkGWowsMwHssywbIBSYByaRe+tSK/FK1/Re/EBkIM8+hhuQLASAquKNBP2oOkbYr8TgzxcscccjEW3f9l2bxr0FemzQcJB+5sY00lRxqfIZl7JuJZsD83qOjaRr6ZPzeTHPDNmnmPRFQ21uKHWxVQl80EUwHMsooS/QZp9IS5yzKjQ6XLByCE/xoE5gXEhf6qBt/J2mxiNIg+LT4wqv36CLFSi44SlDwZNblODlHMcaVBBg72KvyXcYkiQY+50XVNpYsZz8=
  file: to-travis/kube-cert.bz2
  on:
    tags: true
  